### ISSUE TITLE
Phrases to dig for

### ISSUE THREAD

**Issue by jschmid1** [denisok/elk_supportconfig#1]
for salt/deepsea

``` text
SaltRenderError: Jinja variable 'salt.utils.templates.AliasedLoader
object' has no attribute 'WHAT_EVER_MODULE'
```
can also be limited to grep to `SaltRenderError`

```text
The minion function caused an exception
```
after this there is _usually_ a traceback which gives you a good insight..

``` text
Module function cephprocesses.wait executed
```

means that something something timed out and needs to be investigated

I'll update the issue once I find more

**Comment by denisok** [comment]
The only problem with `SaltRenderError` - I seen it only from deepsea log which is not supported for this moment. I guess it will be the same in syslog ?
@jschmid1 if deepsea log is already in support config - we need to add new feature to import it, as it has different format from syslog.

**Comment by jschmid1** [comment]
> The only problem with SaltRenderError - I seen it only from deepsea log which is not supported for this moment. I guess it will be the same in syslog ?

That I don't know..

> if deepsea log is already in support config - we need to add new feature to import it, as it has different format from syslog.

Yeh, I think that's needed
